apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portfolio-app.fullname" . }}-db
  labels:
    {{- include "portfolio-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "postgresql://{{ .Values.config.database.user }}:{{ .Values.config.database.password | default "changeme" }}@{{ .Values.config.database.host }}:{{ .Values.config.database.port }}/{{ .Values.config.database.name }}"
