apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    url: http://loki:3100
    jsonData:
      maxLines: 1000

  - name: Tempo
    type: tempo
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      tracesToLogs:
        datasourceUid: loki
